spring.application.name= PerfulandiaApplication (dev)
#Indica el puerto que usara el microservicio
server.port= 8081
# Configuración de la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_productos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#usuario BD
spring.datasource.username= root
spring.datasource.password=system


#spring.jpa.hibernate.ddl-auto=update -> esto actualiza la base de datos del modelo que ya tiene
#spring.jpa.hibernate.ddl-auto=none-> esto no hace nada con la base de datos
#spring.jpa.hibernate.ddl-auto=create-drop-> crea y elimina cada vez que se inicia, sirve para pruebas
#create-> crea la base de datos cada vez que se inicia, elimina la anterior
spring.jpa.hibernate.ddl-auto=create

#muestra las consultas SQL en la consola
spring.jpa.show-sql=true
#formatea la salida de las consultas SQL para ver mejor la estructura 
spring.jpa.properties.hibernate.format_sql=true

#especifica el dialecto de la base de datos que se está utilizando, en este caso MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

